//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBlog()
        {
            this.TblYorumlar = new HashSet<TblYorumlar>();
        }
    
        public int Id { get; set; }
        public string Başlık { get; set; }
        public string İçerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Tür { get; set; }
        public Nullable<int> Kategori { get; set; }
        public string Görsel { get; set; }
    
        public virtual TblKategori TblKategori { get; set; }
        public virtual TblTürler TblTürler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblYorumlar> TblYorumlar { get; set; }
    }
}
